# -*- coding: utf-8 -*-
"""CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a6eD7bCtyP77F6PfQOHQWmi6gM_Y422k
"""

import warnings
warnings.filterwarnings("ignore")

import os
path="/content/drive/MyDrive/Brain Tumor Data Set"
os.listdir(path)

import numpy as np
import matplotlib.pyplot as plt
import shutil
import math
import glob

!unzip /content/drive/MyDrive/Braintumor.zip -d /content

root="/content/Brain Tumor Data Set/Brain Tumor Data Set"
numimages={}
for dir in os.listdir(root):
  numimages[dir]=len(os.listdir(os.path.join(root,dir)))
numimages

#train:70% val:15% test:15%

def folder(path,split):
  if not os.path.exists("./"+path):
    os.mkdir("./"+path)
    for dir in os.listdir(root):
      os.makedirs("./"+path+"/"+dir)
      for img in np.random.choice(a=os.listdir(os.path.join(root,dir)),size=(math.floor(split*numimages[dir]-5)),replace=False):
        orig=os.path.join(root,dir,img)
        dest=os.path.join("./",path,dir)
        shutil.copy(orig,dest)
        os.remove(orig)
  else:
    print(f"{path}exists")

path="train"
split=0.7
folder(path,split)

folder("val",0.15)
folder("test",0.15)

#Model
from keras.layers import Conv2D,MaxPool2D,Dense,Dropout,Flatten,BatchNormalization
from keras.models import Sequential
from keras.preprocessing.image import load_img,img_to_array
import keras

model=Sequential()
model.add(Conv2D(filters=16,kernel_size=(3,3),activation="relu",input_shape=(224,224,3)))


model.add(Conv2D(filters=36,kernel_size=(3,3),activation="relu"))
model.add(MaxPool2D(pool_size=(2,2)))

model.add(Conv2D(filters=64,kernel_size=(3,3),activation="relu"))
model.add(MaxPool2D(pool_size=(2,2)))

model.add(Conv2D(filters=128,kernel_size=(3,3),activation="relu"))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Dropout(rate=0.25))

model.add(Dense(units=64,activation="relu"))
model.add(Flatten())
model.add(Dropout(rate=0.25))

model.add(Dense(units=1,activation="sigmoid"))
model.summary()

model.compile(optimizer="adam",loss=keras.losses.binary_crossentropy,metrics=["accuracy"])

#Data prep using Data Generator
from tensorflow.keras.preprocessing.image import ImageDataGenerator

def prepocess(path):
  imagedata=ImageDataGenerator(rescale=1/255,shear_range=0.2,zoom_range=0.2,horizontal_flip=True)
  image=imagedata.flow_from_directory(directory=path,target_size=(224,224),batch_size=32,class_mode="binary")
  return image

path="/content/train"
traindata=prepocess(path)

def prepocess1(path):
  imagedata=ImageDataGenerator(rescale=1/255)
  image=imagedata.flow_from_directory(directory=path,target_size=(224,224),batch_size=32,class_mode="binary")
  return image

path="/content/test"
testdata=prepocess1(path)

path="/content/val"
valdata=prepocess(path)

#earlystopping
from keras.callbacks import EarlyStopping,ModelCheckpoint
es=EarlyStopping(monitor="val_accuracy",min_delta=0.1,verbose=1,mode="auto",patience=5)
ms=ModelCheckpoint(monitor="val_accuracy",mode="auto",verbose=1,filepath="./best.h5",save_best_only=True)
cd=[es,ms]

h=model.fit(traindata,steps_per_epoch=8,epochs=32,verbose=1,validation_data=valdata,validation_steps=16,callbacks=cd)

hist=h.history
hist.keys()

plt.plot(hist["accuracy"])
plt.plot(hist["val_accuracy"],c="red")
plt.title("acc vs val_acc")

plt.plot(hist["loss"])
plt.plot(hist["val_loss"],c="pink")
plt.title("loss vs val_loss")

#model metrics
from tensorflow.keras.models import load_model
model=load_model("/content/best.h5")

loss, acc = model.evaluate(testdata)
print("Test accuracy:", acc*100)
print("Test loss:", loss*100)

from keras.preprocessing.image import load_img,img_to_array

from tensorflow.keras.preprocessing.image import load_img, img_to_array
import numpy as np

p = "/content/Brain Tumor Data Set/Brain Tumor Data Set/Brain Tumor/Cancer (1303).jpg"
img = load_img(p, target_size=(224, 224))
inparr = img_to_array(img) / 255.0
plt.imshow(inparr)
inparr = np.expand_dims(inparr, axis=0)

pred_prob = model.predict(inparr)
pred_class = (pred_prob > 0.5).astype(int)

print("Prediction probability:", pred_prob[0][0])
print("Predicted class:", pred_class[0][0])

